engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: ".eslintrc"
ratings:
  paths:
    - "*.js"
    - "scripts/*.js"
    - "site/*.js"
    - "packages/*/*.js"
    - "packages/*/demo/*.js"
