engines:
  eslint:
    enabled: true
    channel: "eslint-3"
exclude_paths:
  - "build/"
  - "packages/*/build/"
  - "docs/"
  - "public/"
  - "LICENSE"
  - "**.md"
  - "**.html"
  - "**.json"
  - "**.styl"
  - "**.yml"
