branches:
  only: master

language: node_js
node_js: "7"

cache:
  directories:
    - "node_modules"

script:
  - "npm i"
  - "npm run bootstrap"
  - "npm run coverage -- --silent"
  - "node_modules/.bin/codecov"
