branches:
  only: master
language: node_js
node_js: '7'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run bootstrap
  - npm run build:js:packages
  - npm run coverage -- --silent
  - node_modules/.bin/codecov
after_success:
  - if [ $TRAVIS_BRANCH = 'master' ]; then
      eval "$(ssh-agent -s)";
      chmod 600 .travis/deploy_key.pem;
      ssh-add .travis/deploy_key.pem;
      git clone git@github.com:enigma-io/boundless.git boundless;
      cd boundless;
      npm run release;
      git config user.email "travis@travis-ci.com";
      git config user.name "Travis";
      git add .;
      git commit -m "Push assets built by job $TRAVIS_BUILD_NUMBER [skip ci]";
      git push -f git@github.com:enigma-io/boundless.git HEAD:master;
    fi
