branches:
  only: master
language: node_js
node_js: '7'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run bootstrap
  - npm run build:js:packages
  - npm run coverage -- --silent
  - node_modules/.bin/codecov
