---
- hosts: boundless-docs
  vars:
    user: boundless
    home_dir: /home/{{ user }}
    app_dir: "{{ home_dir }}/app"
    nginx_dir: "/usr/local/etc/nginx"

  handlers:
    - name: Restart NGINX
      become: true
      become_user: root
      become_method: su
      service: name=nginx enabled=yes state=restarted

  tasks:
    - name: Create the boundless user
      become: true
      become_user: root
      become_method: su
      user: name={{ user }} shell=/sbin/nologin

    - name: Create the destination folder for the boundless code
      become: true
      become_user: root
      become_method: su
      file: path={{ app_dir }} owner={{ user }} mode=0775 state=directory recurse=yes

    - name: Copy over the boundless source
      become: true
      become_user: root
      become_method: su
      copy: src=../site/public/ dest={{ app_dir }}

    - name: Change owner of boundless source
      become: true
      become_user: root
      become_method: su
      file: path={{ app_dir }} owner={{ user }} recurse=yes

    - name: Install the NGINX vhost config for boundless
      become: true
      become_user: root
      become_method: su
      template: src=vhost.conf dest={{ nginx_dir }}/sites-available/boundless.conf mode=0774 owner={{ user }}

    - name: Symlink vhost
      become: true
      become_user: root
      become_method: su
      file: src={{ nginx_dir }}/sites-available/boundless.conf dest={{ nginx_dir }}/sites-enabled/boundless.conf mode=0774 owner={{ user }} state=link force=yes
      notify: Restart NGINX
