---
- hosts: uikit-docs
  vars:
    user: uikit
    home_dir: /home/{{ user }}
    app_dir: "{{ home_dir }}/app"
    nginx_dir: "/usr/local/etc/nginx"

  handlers:
    - name: Restart NGINX
      sudo: true
      service: name=nginx enabled=yes state=restarted

  tasks:
    - name: Install server dependencies
      sudo: yes
      pkgng: name={{ item }}
      with_items:
        - rsync

    - name: Create the uikit user
      sudo: true
      user: name={{ user }} shell=/sbin/nologin

    - name: Copy over the uikit source
      sudo: true
      synchronize: src=../site/dist/ dest={{ app_dir }}

    - name: Change owner of uikit source
      sudo: true
      file: path={{ app_dir }} owner={{ user }} recurse=yes

    - name: Install the NGINX vhost config for uikit
      sudo: true
      template: src=vhost.conf dest={{ nginx_dir }}/sites-available/uikit.conf mode=0774 owner={{ user }}

    - name: Symlink vhost
      sudo: true
      file: src={{ nginx_dir }}/sites-available/uikit.conf dest={{ nginx_dir }}/sites-enabled/uikit.conf mode=0774 owner={{ user }} state=link force=yes
      notify: Restart NGINX
