---
- hosts: uikit-docs
  vars:
    nginx_dir: "/usr/local/etc/nginx"

  handlers:
    - name: Restart NGINX
      become: true
      become_user: root
      become_method: su
      service: name=nginx enabled=yes state=restarted

  tasks:
    - name: Install server dependencies
      become: true
      become_user: root
      become_method: su
      pkgng: name={{ item }}
      with_items:
        - nginx

    - name: Create nginx directory
      become: true
      become_user: root
      become_method: su
      file: path={{ nginx_dir }} state=directory mode=0774

    - name: Install the NGINX config
      become: true
      become_user: root
      become_method: su
      template: src=server.conf dest={{ nginx_dir }}/nginx.conf mode=0774
      notify: Restart NGINX

    - name: Create vhost sites-available directory
      become: true
      become_user: root
      become_method: su
      file: path={{ nginx_dir }}/sites-available state=directory mode=0774

    - name: Create vhost sites-enabled directory
      become: true
      become_user: root
      become_method: su
      file: path={{ nginx_dir }}/sites-enabled state=directory mode=0774

    - name: Enable NGINX
      become: true
      become_user: root
      become_method: su
      lineinfile:
        dest=/etc/rc.conf
        line="nginx_enable=\"YES\""
        state=present
        insertafter=EOF

    - name: Start NGINX
      become: true
      become_user: root
      become_method: su
      service: name=nginx enabled=yes state=started
